name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0.30', '8.1.27', '8.2.17', '8.3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: PHP_VERSION=${{ matrix.php-version }} docker compose build debian

      - name: Build PHP extension
        run: PHP_VERSION=${{ matrix.php-version }} docker compose run debian ./build.sh

      - name: Run tests
        run: |
          PHP_VERSION=${{ matrix.php-version }} docker compose run debian bash -c "cd /usr/src/myapp && cat > tests/001.phpt << 'EOT'
          --TEST--
          Check if phook extension is loaded
          --EXTENSIONS--
          phook
          --FILE--
          <?php
          ob_start();
          printf('The extension \"phook\" is available, version %s', phpversion('phook'));
          \$output = ob_get_clean();
          echo \$output;
          ?>
          --EXPECTF--
          The extension \"phook\" is available, version %s
          EOT
          && php -d extension=\$(pwd)/modules/phook.so -d phook.display_warnings=Off run-tests.php -m tests/001.phpt 2>/dev/null"

      - name: Check code formatting
        run: PHP_VERSION=${{ matrix.php-version }} docker compose run debian ./format.sh

      - name: Verify clean git status (no formatting changes)
        run: |
          git diff --exit-code || {
            echo "Code formatting issues detected. Please run 'make format' locally and commit changes."
            exit 1
          }
