name: Verify Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'DEVELOPMENT.md'
      - '.github/workflows/verify-documentation.yml'

jobs:
  verify-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: PHP_VERSION=8.3.10 docker compose build debian

      - name: Test documentation steps
        run: |
          docker compose run debian bash -c "
            set -e
            # Test steps from DEVELOPMENT.md
            phpize
            ./configure
            make
            make test
            make install
            php -dextension=phook -m | grep -q phook
            
            # Test valgrind steps
            php run-tests.php -d extension=\$(pwd)/modules/phook.so -m tests/001.phpt
            
            # Clean up
            make clean
          "
